name = "afiexplorer-api-v2"
main = "src/index.ts"
compatibility_date = "2023-10-10"

[[kv_namespaces]]
binding = "KV"
# Obtain `id` from your Cloudflare Workers KV dashboard
id = "YOUR_ID_HERE"

[triggers]
crons = ["*/10 * * * *"]
